stages:
    - deploy
    - deploy-aws

deploydevelop:
    image: ilyasemenov/gitlab-ci-git-push
    stage: deploy
    script: git-push dokku@dokku1.solidstategroup.com:bullet-train-api-dev
    only:
        - develop

deploymaster:
    image: ilyasemenov/gitlab-ci-git-push
    stage: deploy
    script: git-push dokku@dokku1.solidstategroup.com:bullet-train-api
    only:
        - master

deployawsstaging:
    image: twstuart/elasticbeanstalk-pipenv
    stage: deploy-aws
    script:
        - export DATABASE_URL='${DATABASE_URL_STAGING}'
        - pipenv lock --requirements > ./src/requirements.txt
        - sh generate.sh
        - cd src
        - eb deploy $EB_ENVIRONMENT_STAGING
    only:
        - develop-aws