repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [--config, api/pyproject.toml, --config, "src = ['api']", --fix]
      # Run the formatter.
      - id: ruff-format
        args: [--config, api/pyproject.toml, --config, "src = ['api']"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: prettier
        additional_dependencies:
          - prettier@3.4.2
        args:
          - --check
        types: [javascript, jsx, ts, tsx, markdown, mdx, html, css, json, yaml]
      - id: generate-docs
        name: generate-docs
        language: system
        entry: make -C api generate-docs
        pass_filenames: false
        types: [python,toml]
      - id: python-typecheck
        name: python-typecheck
        language: system
        entry: poetry -C api run mypy .
        require_serial: true
        pass_filenames: false
        types: [python]
        stages: [pre-push]

  - repo: https://github.com/python-poetry/poetry
    rev: 2.2.1
    hooks:
      - id: poetry-check
        args: ["-C", "api"]

default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit]

ci:
  skip: [generate-docs, python-typecheck]
  autoupdate_commit_msg: "ci: pre-commit autoupdate"
