branch-defaults:
  develop:
    environment: null
    group_suffix: null
global:
  application_name: bullet-train-api
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
