name: Run API tests with private package

on:
  pull_request:
    branches:
      - main
    types: [labeled]

defaults:
  run:
    working-directory: api

env:
  FLAGSMITH_SAML_REVISION: v1.6.1
  FLAGSMITH_RBAC_REVISION: v0.7.0
  FLAGSMITH_AUTH_CONTROLLER_REVISION: v0.1.0

jobs:
  test:
    if: ${{ github.event.label.name == 'api' }}
    runs-on: ubuntu-latest
    name: API Tests

    services:
      postgres:
        image: postgres:15.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Cloning repo
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install Dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "https://${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}:@github.com" > ${HOME}/.git-credentials
          git config --global credential.helper store
          make install-packages opts="--with saml,auth-controller,workflows"
          rm -rf ${HOME}/.git-credentials

      - name: Install SAML Dependencies
        run: sudo apt-get install -y xmlsec1

      - name: Get workflows-logic package version
        id: workflow-version
        run: |
          tag=$(grep -A 1 "\[tool.poetry.group.workflows.dependencies\]" pyproject.toml | awk -F '"' '{printf $4}')
          echo "Workflow Tag: $tag"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Checkout workflow package
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-workflows
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ steps.workflow-version.outputs.tag }}
          path: ./workflows_logic

      - name: integrate workflow tests
        run: ln -s $GITHUB_WORKSPACE/workflows_logic/tests tests/workflow_logic_tests
        shell: bash
        working-directory: api

      - name: Checkout rbac package
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-rbac
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.FLAGSMITH_RBAC_REVISION }}
          path: ./flagsmith-rbac

      - name: Integrate RBAC module
        run: mv $GITHUB_WORKSPACE/flagsmith-rbac/rbac .
        shell: bash

      - name: integrate rbac tests
        run: ln -s $GITHUB_WORKSPACE/flagsmith-rbac/tests tests/rbac_tests
        shell: bash
        working-directory: api

      - name: Checkout Auth Controller package
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-auth-controller
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.FLAGSMITH_AUTH_CONTROLLER_REVISION }}
          path: ./flagsmith-auth-controller

      - name: Integrate Auth Controller module
        run: mv $GITHUB_WORKSPACE/flagsmith-auth-controller/auth_controller .
        shell: bash

      - name: integrate auth_controller tests
        run: ln -s $GITHUB_WORKSPACE/flagsmith-auth-controller/tests tests/auth_controller_tests
        shell: bash
        working-directory: api

      - name: Checkout SAML package
        uses: actions/checkout@v4
        with:
          repository: flagsmith/flagsmith-saml
          token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
          ref: ${{ env.flagsmith_saml_revision }}
          path: ./flagsmith-saml

      - name: Integrate SAML module
        run: mv $GITHUB_WORKSPACE/flagsmith-saml/saml .

      - name: integrate saml tests
        run: ln -s $GITHUB_WORKSPACE/flagsmith-saml/tests tests/saml_tests
        shell: bash
        working-directory: api

      - name: Run Tests
        env:
          DOTENV_OVERRIDE_FILE: .env-ci
        run: make test
