name: API Deploy to Staging ECS

on:
  push:
    branches:
      - main
      - fix(ci)/task-def-version-check-failures
    paths:
      - api/**
      - .github/**
      - infrastructure/aws/staging/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy-ecs:
    uses: ./.github/workflows/.reusable-deploy-ecs.yml
    with:
      environment: staging
    secrets: inherit