name: API Deploy to Staging

on:
    push:
        branches:
            - temp/debug-with-error-log
        paths:
            - 'api/**'
            - '.github/**'

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        name: API Deploy to Staging
        container: flagsmith/eb-cli:latest
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Deploy API to Staging
              uses: ./.github/actions/api-deploy
              with:
                  beanstalk_environment_name: staging-api
                  github_access_token: ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}
                  aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  flagsmith_saml_revision: v0.1.1

    run-tests:
        runs-on: ubuntu-latest
        name: Run E2E Tests
        environment: staging
        needs: deploy-staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Test with Chromedriver
              working-directory: frontend
              env:
                  E2E_TEST_TOKEN_STAGING: ${{ secrets.E2E_TEST_TOKEN }}
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
                  STATIC_ASSET_CDN_URL: /
              run: |
                  wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_96.0.4664.110-1_amd64.deb
                  sudo apt install --allow-downgrades -y ./google-chrome*.deb -f
                  google-chrome --version
                  node -v
                  npm i
                  export ENV=staging;
                  npm run env
                  npm run test
