name: Docker Compose E2E Tests

on:
    # todo: fix in other branches
    push:
        branches:
            - master
            #- feature/ch1382/combine-api-and-fe-docker-repositories # todo: replace
    #pull_request:
    #    branches:
    #        - master

jobs:
    docker:
        timeout-minutes: 10
        runs-on: ubuntu-latest

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Start containers
              run: docker-compose -f "docker/docker-compose.yml" up -d --build

            - name: Install node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: cd frontend; npm install

            - name: Run tests
              run: cd frontend; npm run test

            - name: Stop containers
              if: always()
              run: docker-compose -f "docker-compose.yml" down
