name: Frontend Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/**

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Cloning repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.nvmrc
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

  run-tests:
    needs: run-unit-tests
    runs-on: depot-ubuntu-latest
    name: Run E2E Tests
    environment: production
    concurrency:
      group: e2e-tests-prod
      cancel-in-progress: true

    steps:
      - name: Cloning repo
        uses: actions/checkout@v5
      
      # Temporarily install Firefox 143.0 to avoid test failures as superior versions cause frontend e2e tests to hang
      # To be removed once upstream issue correctly resolved
      - name: Install Firefox 143.0
        run: |
          sudo apt-get remove -y firefox || true
          sudo rm -rf /usr/bin/firefox /usr/lib/firefox*
          
          ARCH=$(uname -m)
          wget -O /tmp/firefox.tar.xz "https://ftp.mozilla.org/pub/firefox/releases/143.0/linux-${ARCH}/en-US/firefox-143.0.tar.xz"
          sudo tar -xJf /tmp/firefox.tar.xz -C /opt
          sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox
          rm /tmp/firefox.tar.xz
          
          firefox --version

      - name: Run E2E tests against production
        uses: ./.github/actions/e2e-tests
        with:
          e2e_test_token: ${{ secrets.E2E_TEST_TOKEN }}
          slack_token: ${{ secrets.SLACK_TOKEN }}
          environment: prod

  deploy-production:
    name: Deploy to Vercel Production
    needs: run-tests
    uses: ./.github/workflows/.reusable-frontend-deploy.yml
    with:
      gh_environment: production
      npm_build_environment: prod
    secrets: inherit

  deploy-demo:
    name: Deploy to Vercel Demo
    needs: run-tests
    uses: ./.github/workflows/.reusable-frontend-deploy.yml
    with:
      gh_environment: demo
      npm_build_environment: prod
    secrets: inherit

  deploy-demo2:
    name: Deploy to Vercel Demo2
    needs: run-tests
    uses: ./.github/workflows/.reusable-frontend-deploy.yml
    with:
      gh_environment: demo2
      npm_build_environment: prod
    secrets: inherit
