name: Frontend Deploy to Vercel Staging

on: pull_request
#todo: update to main
#    push:
#        branches:
#            - main
#        paths:
#            - 'frontend/**'
#            - '.github/**'

defaults:
    run:
        working-directory: frontend

jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        name: Deploy to Vercel Staging
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: npm-${{ hashFiles('package-lock.json') }}
                  restore-keys: npm-

            - name: Deploy to Vercel
              env:
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  ENV: staging
              run: |
                  npm ci --only=prod
                  npm run env
                  npm run dotenv
                  npm run bundlevercel
                  vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
