name: Frontend Deploy to Production

on:
    push:
        branches:
            - main
        paths:
            - 'frontend/**'
            - '.github/**'

defaults:
    run:
        working-directory: frontend

jobs:
    run-tests:
        runs-on: ubuntu-latest
        name: Run E2E Tests
        environment: production

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Run E2E Tests
              env:
                  E2E_TEST_TOKEN_PROD: ${{ secrets.E2E_TEST_TOKEN }}
                  ENV: prod
              run: |
                  wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_91.0.4472.114-1_amd64.deb
                  sudo apt install --allow-downgrades -y ./google-chrome*.deb -f
                  google-chrome --version
                  node -v
                  npm i
                  npm run env
                  npm run test

    deploy-production:
        runs-on: ubuntu-latest
        name: Deploy to Production
        environment: production
        needs: run-tests

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: bullet-train-front-end-prod
                  service_account_key: ${{ secrets.FRONTEND_GOOGLECLOUD_SERVICEACCOUNT_KEY }}

            - name: Deploy to App Engine
              env:
                  STATIC_ASSET_CDN_URL: https://cdn.flagsmith.com
                  ENV: prod
                  AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
                  DELIGHTED_API_KEY: ${{ secrets.DELIGHTED_API_KEY }}
                  CRISP_WEBSITE_ID: ${{ secrets.CRISP_WEBSITE_ID }}
                  CAPTERRA_API_KEY: ${{ secrets.CAPTERRA_API_KEY }}
                  DEPLOYMENT_SLACK_CHANNEL: ${ secrets.DEPLOYMENT_SLACK_CHANNEL }}
                  E2E_SLACK_CHANNEL: ${{ secrets.E2E_SLACK_CHANNEL }}
                  EVENTS_SLACK_CHANNEL: ${{ secrets.EVENTS_SLACK_CHANNEL }}
                  ENABLE_FLAG_EVALUATION_ANALYTICS: ${{ secrets.ENABLE_FLAG_EVALUATION_ANALYTICS }}
                  ENABLE_INFLUXDB_FEATURES: ${{ secrets.ENABLE_INFLUXDB_FEATURES }}
                  GOOGLE_ANALYTICS_API_KEY: ${{ secrets.GOOGLE_ANALYTICS_API_KEY }}
                  LINKEDIN: ${{ secrets.LINKEDIN }}
                  MIXPANEL_API_KEY: ${{ secrets.MIXPANEL_API_KEY }}
                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
              run: |
                  npm i
                  npm run env
                  npm run dotenv
                  npm run bundle
                  gcloud app deploy --quiet
