name: Frontend Deploy to Staging

on:
    push:
        branches:
            - main
            - chore/*

defaults:
    run:
        working-directory: frontend

jobs:
    run-tests:
      runs-on: ubuntu-latest
      name: Run E2E Tests
      environment: staging
      container: kylessg/bullet-train-nightwatch:1.1

      steps:
        - name: Cloning repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Setup Node.js 14.x
          uses: actions/setup-node@v1
          with:
            node-version: 14.x

        - name: Setup npm environment
          env:
            ENV: staging
          run: |
            npm i
            npm run env

        - name: Run E2E Tests
          env:
            E2E_TEST_TOKEN_STAGING: ${{ secrets.E2E_TEST_TOKEN }}
          run: |
            google-chrome --version
            node -v
            npm run test

    deploy-staging:
        runs-on: ubuntu-latest
        name: Deploy to Staging
        environment: staging
        needs: run-tests

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Setup npm environment
              env:
                ENV: staging
              run: npm i && npm run env

            - name: Setup Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.2.0
              with:
                  project_id: bullet-train-front-end-staging
                  service_account_key: ${{ secrets.FRONTEND_GOOGLECLOUD_SERVICEACCOUNT_KEY }}

            - name: Deploy to App Engine
              run: |
                npm run dotenv
                npm run bundledev
                gcloud app deploy --quiet
