name: Benchmark Flagsmith API

on:
    - push
    # todo: reinstate
    # schedule:
    #    - cron: '0 4 * * 1-5' # Mon-Fri 4AM UTC

concurrency: 'benchmarks' # Ensure only one of this runs at a time

jobs:
    run-benchmarks:
        name: SDK benchmark
        runs-on: ubuntu-latest

        env:
            DJANGO_ALLOWED_HOSTS: '*'
            DATABASE_URL: postgres://postgres:postgres@localhost:5432/flagsmith
            SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
            DJANGO_SETTINGS_MODULE: app.settings.test
            FE_E2E_TEST_USER_EMAIL: nightwatch@solidstategroup.com

        services:
            postgres:
                image: postgres:11.12-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: flagsmith
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            #- name: Check out Flagsmith/benchmarks-results repo
            #  uses: actions/checkout@v2
            #  with:
            #      path: api/benchmarks/results
            #      repository: Flagsmith/benchmark-results
            #token: ${{ secrets.FLAGSMITH_BOT_GITHUB_TOKEN }}

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Install python dependencies
              run: |
                  cd api
                  python -m pip install -r requirements-dev.txt
                  python -m pip install -r requirements.txt

            - name: Install asv
              run: pip install git+https://github.com/airspeed-velocity/asv.git virtualenv

            - name: Set up Flagsmith
              run: |
                  python manage.py migrate
