name: Update Flagsmith Defaults

on:
  schedule:
    - cron: 0 8 * * *
  pull_request_target:
  push:

defaults:
  run:
    working-directory: api

jobs:
  update_server_defaults:
    runs-on: ubuntu-latest
    name: Update API Flagsmith Defaults
    env:
      FLAGSMITH_API_URL: https://edge.api.flagsmith.com/api/v1
      FLAGSMITH_SERVER_KEY: ${{ secrets.FLAGSMITH_SERVER_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip

      - name: Install Dependencies
        run: make install

      - name: Update defaults
        run: python manage.py updateflagsmithdefaults

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update API Flagsmith Defaults
          branch: chore/update-api-flagsmith-defaults
          delete-branch: true
          title: 'chore: update API Flagsmith defaults'
          labels: api
