name: Update Flagsmith Defaults

on:
  schedule:
    - cron: 0 8 * * *

defaults:
  run:
    working-directory: api

jobs:
  update_server_defaults:
    runs-on: depot-ubuntu-latest
    name: Update API Flagsmith Defaults
    env:
      FLAGSMITH_ON_FLAGSMITH_SERVER_API_URL: https://edge.api.flagsmith.com/api/v1
      FLAGSMITH_ON_FLAGSMITH_SERVER_KEY: ${{ secrets.FLAGSMITH_ON_FLAGSMITH_SERVER_KEY }}

    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: make install

      - name: Update defaults
        run: uv run python manage.py updateflagsmithenvironment

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update API Flagsmith Defaults
          branch: chore/update-api-flagsmith-environment
          delete-branch: true
          title: 'chore: update Flagsmith environment document'
          labels: api
